development:
  adapter: postgresql
  encoding: utf8
  database: sis_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: sis_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: sis_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST